### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by minervamaga** [randomtdev/nexusmods_downloadfix#3]
Looks like Nexus might have found a way to block this.  The fast/slow page doesn't load, but the download buttons change to say downloading, then reset.  No download dialogue box either.

**Comment by Stifling-Bossness** [comment]
Trying to use this to do manual downloads ends up with no download, but the URL gets appended with 
`#ERROR-download-location-not-found` Didn't have any issues downloading with a manager, and disabling the script allows normal manual downloads.

**Comment by cvsickle** [comment]
I'm having the same issue.

**Comment by Espio419** [comment]
Right clicking manual download and choosing open in new tab works.

**Comment by cvsickle** [comment]
It looks like they did it on purpose.

[https://www.reddit.com/r/skyrimmods/comments/ernl7e/is_anybody_else_unable_to_manually_download_files/ff5qs2n?utm_source=share&utm_medium=web2x](url)

"That script was breaking the download history by circumventing an important step that included the code which increases the download counter. So that would affect things like the mods you downloaded showing in your history, the ability to endorse mods, the mod author's Donation Points, and so on and so forth.

We couldn't care much less about the scripts people try and use to circumvent the Premium screen - but we do care when it starts breaking other mechanisms of the site. Nor could we care much less if changes we make break those scripts."

This appears to be, at least, partially untrue. My download history is in tact from the entire time I was using the script and I was able to endorse mods without a problem. I obviously can't speak to the donation points though.

**Comment by anakhasilver** [comment]
It's definitely a lie about the download history. Mine's also intact.

**Comment by ThatSicklyPup** [comment]
Having the same issue and can confirm that my download history is intact.

**Comment by randomtdev** [comment]
I've fixed this and an update will be out shortly; Manual downloads will be much faster than before.

**Comment by randomtdev** [comment]
This is fixed now.

**Comment by cvsickle** [comment]
Thank you! I'll be using this later tonight.
